# Generated by Django 6.0.6 on 2026-06-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('university', 'University Administrator'), ('mentor', 'University Mentor'), ('student', 'Student / Internship Seeker'), ('company', 'Company Administrator'), ('supervisor', 'Company Supervisor')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('university_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='student_portal.userprofile')),
                ('assigned_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='student_portal.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150)),
                ('skills', models.TextField(help_text='Comma-separated skills list')),
                ('objective', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='student_portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(default=5)),
                ('communication', models.IntegerField(default=5)),
                ('teamwork', models.IntegerField(default=5)),
                ('professionalism', models.IntegerField(default=5)),
                ('punctuality', models.IntegerField(default=5)),
                ('goal_achievement', models.IntegerField(default=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_evaluations', to='student_portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_company', models.CharField(max_length=150)),
                ('credential_type', models.CharField(choices=[('certificate', 'Completion Certificate'), ('excellence', 'Excellence Award'), ('best_performer', 'Best Performer Award'), ('innovation', 'Innovation Award')], max_length=30)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('uid_verification_code', models.CharField(max_length=50, unique=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('education_level', models.CharField(default='Bachelor', max_length=100)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_portal.internshipnature')),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted / Offered'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('cvr_file', models.FileField(blank=True, null=True, upload_to='credentials/cv/')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='credentials/transcripts/')),
                ('university_letter', models.FileField(blank=True, null=True, upload_to='credentials/letters/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student_portal.internshiplisting')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to='student_portal.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(help_text='1 to 8 matching the Ahlia training guide')),
                ('work_done_summary', models.TextField(help_text="Student's logged weekly details")),
                ('status', models.CharField(choices=[('pending_company', 'Pending Supervisor Review'), ('pending_mentor', 'Pending Mentor Final Sign-off'), ('approved', 'Fully Approved & Verified'), ('rejected_company', 'Returned by Company for Fixes'), ('rejected_mentor', 'Returned by Mentor for Fixes')], default='pending_company', max_length=25)),
                ('supervisor_feedback', models.TextField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile')),
            ],
            options={
                'unique_together': {('student', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('device_api_status', models.CharField(default='Synchronized (Mobile GPS)', max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
