# Generated by Django 6.0.6 on 2026-06-09 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshiplisting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='internshiplisting',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='issuedcredential',
            name='student',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='performanceevaluation',
            name='supervisor',
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='studentresume',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_mentor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university_name',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='record_type',
            field=models.CharField(choices=[('regular', 'Regular Shift'), ('emergency_break', 'Emergency Break')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='studentresume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='device_api_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile'),
        ),
        migrations.AlterField(
            model_name='studentresume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='required_hours',
            field=models.DecimalField(decimal_places=2, default=240.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
        migrations.DeleteModel(
            name='InternshipListing',
        ),
        migrations.DeleteModel(
            name='InternshipNature',
        ),
        migrations.DeleteModel(
            name='IssuedCredential',
        ),
        migrations.DeleteModel(
            name='PerformanceEvaluation',
        ),
        migrations.DeleteModel(
            name='ProgressReport',
        ),
    ]
