# Generated by Django 6.0.6 on 2026-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_remove_internshiplisting_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('BUS', 'Business & Finance'), ('ENG', 'Engineering')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinator_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('date_affiliated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
