# Generated by Django 6.0.6 on 2026-06-24 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_trainingtrack_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtrack',
            name='department',
        ),
        migrations.AddField(
            model_name='trainingtrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 24, 19, 56, 42, 749969, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtrack',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingtrack',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
