# Generated by Django 6.0.6 on 2026-06-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0007_company_alter_university_options_companysupervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtrack',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trainingtrack',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('BUS', 'Business & Finance'), ('ENG', 'Engineering')], default='IT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_portal.trainingtrack'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='student_portal.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_portal.university'),
        ),
        migrations.AlterField(
            model_name='trainingtrack',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtrack',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
