# Generated by Django 6.0.6 on 2026-06-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0008_remove_trainingtrack_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Company Supervisor'), ('university_mentor', 'University Mentor'), ('university_admin', 'University Coordinator')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('tasks_completed', models.TextField(help_text='What did you accomplish this week?')),
                ('challenges_faced', models.TextField(blank=True, help_text='Any technical issues or blockers?')),
                ('status', models.CharField(choices=[('pending', 'Pending Supervisor Approval'), ('approved', 'Approved - Pending Mentor Grade'), ('graded', 'Graded & Completed')], default='pending', max_length=20)),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('mentor_grade', models.CharField(blank=True, help_text='e.g., A, B, Pass', max_length=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='student_portal.userprofile')),
            ],
        ),
    ]
